apiVersion: v1
kind: PersistentVolume
metadata:
  name: my-pv-volume
  namespace: macarious
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: manual
  hostPath:
    path: /mnt/data/bookmanage
