apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: my-pv-claim2
  namespace: fareed 
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: manual
  resources:
    requests:
      storage: 1Gi
